{
	'star-flow'			: 	set(['guoxiang.lgx', 'taiqi.zyl']),
	'b2b-flow-st'			: 	set(['guoxiang.lgx', 'taiqi.zyl']),
	'test-b2b'			: 	set(['guoxiang.lgx', 'taiqi.zyl']),
	'star-p4p'			: 	set(['guoxiang.lgx', 'taiqi.zyl']),
	'star-b2c'			: 	set(['guoxiang.lgx', 'taiqi.zyl']),
	'star-b2b'			: 	set(['guoxiang.lgx', 'taiqi.zyl']),
	'star-business'			:	set(['guoxiang.lgx', 'taiqi.zyl']),
	'subscribe-example' 		: 	set(['guoxiang.lgx']),
	'effect-pem'			:	set(['qingwu', 'minzhan', 'jiuling.ypf']),
	'effect-test'			:	set(['qingwu', 'minzhan', 'jiuling.ypf']),
	'preference_cart'		:	set(['songzhi','yishan','qingjian']),
	'preference_browse'		: 	set(['songzhi','yishan','qingjian']),
	'preference_collect'		: 	set(['songzhi','yishan','qingjian']),
}
